"use client";

import Link from "next/link";

type MenuDrawerProps = { isOpen: boolean; onClose: () => void; selectedCategory: string; onSelectCategory: (category: string) => void };

export default function MenuDrawer({ isOpen, onClose, selectedCategory, onSelectCategory }: MenuDrawerProps) {
  if (!isOpen) return null;
  return <div className="drawer-layer" role="presentation" onMouseDown={onClose}><aside className="menu-drawer" role="dialog" aria-modal="true" aria-label="Menu principal" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-top"><Link className="reader-brand" href="/" onClick={onClose}><span className="brand-mark brand-mark-caramel">V</span><span><strong>Verso</strong><small>poemas para ler devagar</small></span></Link><button className="drawer-close" type="button" onClick={onClose} aria-label="Fechar menu">×</button></div><nav className="drawer-nav"><p className="drawer-label">navegar</p><Link className={`drawer-link ${selectedCategory === "Todos os poemas" ? "selected" : ""}`} href="/" onClick={onClose}><span>▣</span> Todos os poemas</Link><button className={`drawer-link ${selectedCategory === "Favoritos" ? "selected" : ""}`} type="button" onClick={() => onSelectCategory("Favoritos")}><span>♡</span> Favoritos</button></nav><div className="category-area"><p className="drawer-label">categorias</p><div className="category-list">{["Amor", "Saudade", "Natureza", "Noite", "Alma"].map((category) => <button className={selectedCategory === category ? "selected" : ""} type="button" key={category} onClick={() => onSelectCategory(category)}>{category}</button>)}</div></div><div className="drawer-bottom"><div className="daily-thought"><p className="drawer-label">✧ pensamento do dia</p><q>A leitura em silêncio é também uma forma de companhia.</q></div><p className="drawer-description">Verso reúne poemas do domínio público da literatura brasileira, escolhidos para ler sem pressa.</p><div className="drawer-account"><span className="account-avatar">M</span><span><strong>Olá, Marina</strong><small>conta gratuita</small></span><Link href="/configuracoes" onClick={onClose} aria-label="Abrir conta e configurações">›</Link></div><Link className="premium-link" href="/configuracoes#premium" onClick={onClose}>✦ Tornar-se Premium <span>→</span></Link></div></aside></div>;
}